### ISSUE TITLE
Investigate authentication error reporting

### ISSUE THREAD

**Issue by adavidw** [AuthorizeNet/sample-code-python#33] opened 2017-03-28 16:27 UTC
From this issue in the community:
https://community.developer.authorize.net/t5/Integration-and-Testing/IncompleteElementContentError/m-p/57438/

User reports that sending wrong credentials with our sample code returns an "IncompleteElementContentError". Investigate whether better response handling is needed in the sample, or if there are improvements needed to the SDK.

**Comment by gnongsie** [comment] 2018-11-16 05:37
Hi @adavidw ,

We've tested this with our current SDK version and we cannot reproduce this issue.

Even with incorrect credentials, as the OP posted on the forum, we are getting a proper "Invalid Credentials" message and not the "IncompleteElementContentError" message.

I'll close this as it is a non-issue. Thanks for the continued support.

**Closed by gnongsie** 2018-11-16 05:37 UTC
Labels: help wanted
